version: '3.8'

services:
  problems-database:
    build: ./
    command: ./problems-database
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432